print('hello, world')
print ('what is your name bro')
myName = input()
print('its nice to meet you ' + myName)
print('the length of your name is: ')
print (len(myName))
print('What is your age?')
myAge = input()
print('you will be' + str(int(myAge) + 1) + 'in a year')
