print('enter the name of cat 1:')
catName1 = input()
print('enter the name of cat 2:')
catName2 = input()
print('enter the name of cat 3:')
catName3 = input()
print('enter the name of cat 4:')
catName4 = input()
print('enter the name of cat 5:')
catName5 = input()
print('enter the name of cat 6')
catName6 = input()
print(catName1 + ' ' + catName2 + ' ' + catName3 + ' ' + catName4 + ' ' + catName5 + ' ' + catName6)
